ALTER TABLE account ADD COLUMN nickname VARCHAR(255) NOT NULL DEFAULT 'User';
ALTER TABLE account ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE account ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE account ADD COLUMN time_of_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;