spring.application.name=weathertaskbackend
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/weather_task_dashboard_flyway?useSSL=false&serverTimezone=UTC
spring.datasource.username=weather_app
spring.datasource.password=DeinPasswort123!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.security=DEBUG